# Generated by Django 6.1.1 on 2026-09-29 22:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0002_registroauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_o_rif', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre_completo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Pago al contado'), ('FIADO', 'Crédito / fiado')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada totalmente'), ('PENDIENTE', 'Pendiente por pagar')], default='PAGADA', max_length=15)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='usuarios.sede')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.productoinventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_registrados', to=settings.AUTH_USER_MODEL)),
                ('sede_donde_paga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_recibidos', to='usuarios.sede')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sede', 'fecha_apertura'], name='ventas_sede_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tipo_pago', 'estado'], name='ventas_pago_estado_idx'),
        ),
    ]
