# Generated by Django 6.1.1 on 2026-09-29 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0002_registroauditoria'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='abono',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ventas_abono_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ventas_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ventas_detalle_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ventas_detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PAGADA'), ('tipo_pago', 'CONTADO')), models.Q(('estado__in', ['PAGADA', 'PENDIENTE']), ('tipo_pago', 'FIADO')), _connector='OR'), name='ventas_estado_pago_coherente'),
        ),
    ]
