# Generated by Django 6.1.1 on 2026-10-06 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0002_registroauditoria'),
        ('ventas', '0002_abono_ventas_abono_monto_positivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='venta',
            name='ventas_estado_pago_coherente',
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo_pago',
            field=models.CharField(choices=[('PUNTO_DE_VENTA', 'Punto de venta'), ('PAGO_MOVIL', 'Pago móvil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAGADA', 'Pagada totalmente'), ('PENDIENTE', 'Pendiente por pagar'), ('CANCELADA', 'Cancelada')], default='PAGADA', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PAGADA'), ('tipo_pago', 'CONTADO')), models.Q(('estado__in', ['PAGADA', 'PENDIENTE']), ('tipo_pago', 'FIADO')), ('estado', 'CANCELADA'), _connector='OR'), name='ventas_estado_pago_coherente'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.productoinventario'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='usuarios.sede'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta'),
        ),
    ]
