# Generated by Django 6.1.1 on 2026-10-06 18:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0002_registroauditoria'),
        ('ventas', '0003_devolucion_remove_venta_ventas_estado_pago_coherente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CANCELACION', 'Cancelación de venta'), ('DEVOLUCION', 'Devolución de venta')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(blank=True, default='', max_length=180)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venta', to='inventario.productoinventario')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venta', to='usuarios.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venta', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['tipo_evento', 'fecha'], name='venta_evento_tipo_fecha_idx'), models.Index(fields=['venta', 'tipo_evento'], name='venta_evento_venta_tipo_idx')],
            },
        ),
    ]
